# web访问端口
server:
  port: 10000

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://47.103.88.52:3306/foodie-shop?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
