spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root